# -*- coding: utf-8 -*-
"""Excel convert to CSV and JSON.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MyUu3ThFG976X7vnEXD9Hn6C9kYeJUZQ
"""

import pandas as pd
from google.colab import files

# 1. آپلود فایل اکسل
uploaded = files.upload()

import pandas as pd
from google.colab import files

# نام فایل اکسل
excel_file = 'Iran Electricity Portfolio 1967-2016(Million Kwh).xlsx'

# خواندن شیت اول از فایل اکسل
df = pd.read_excel(excel_file)

# ذخیره به فرمت CSV
csv_filename = 'iran_electricity.csv'
df.to_csv(csv_filename, index=False)
print(f"✅ CSV ذخیره شد: {csv_filename}")

# ذخیره به فرمت JSON
json_filename = 'iran_electricity.json'
df.to_json(json_filename, orient='records', indent=2)
print(f"✅ JSON ذخیره شد: {json_filename}")

# دانلود فایل‌ها
files.download(csv_filename)
files.download(json_filename)